common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: picks_admin
  password: secret_db_pwd

development:
  <<: *common
  database: picks_development

test:
  <<: *common
  database: picks_test

production:
  <<: *common
  database: picks_production

backup:
  <<: *common
  database: local_picks_backup

cucumber:
  <<: *test

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000
